Fix check_process
YunoHost-Apps/framaforms_ynh pull request #31
Opened 2020-09-28 08:57 UTC by ericgaspar

## Problem
- *This app fails the CI because the check_process lacks admin, language, expiratio, deletion*

## Solution
- *Fix check_process*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
*If you have access to [App Continuous Integration for packagers](https://yunohost.org/#/packaging_apps_ci) you can provide a link to the package_check results like below, replacing '-NUM-' in this link by the PR number and USERNAME by your username on the ci-apps-dev. Or you provide a screenshot or a pastebin of the results*

[![Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/framaforms_ynh%20PR-NUM-%20(ericgaspar)/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/framaforms_ynh%20PR-NUM-%20(ericgaspar)/)

2020-10-03 16:47 UTC, yalh76 requested changes

2020-10-03 16:47 UTC, yalh76 commented on scripts/restore
> +mkdir -p "$final_path/app/sites/default/files"
I don't think, creates that folder is required

2020-10-03 16:47 UTC, yalh76 commented on manifest.json
> +  "version": "1.0.1~ynh1",
```suggestion
  "version": "1.0.1+200715~ynh3",
```

2020-10-03 16:51 UTC, ericgaspar commented on scripts/restore
> +mkdir -p "$final_path/app/sites/default/files"
If not created, the restore script fails :s

2020-10-03 17:02 UTC, yalh76 commented on scripts/restore
> +mkdir -p "$final_path/app/sites/default/files"
seems strange because you be present as restored during `ynh_restore_file --origin_path="$final_path"`

2020-10-03 17:09 UTC, ericgaspar commented on scripts/restore
> +mkdir -p "$final_path/app/sites/default/files"
I am rerunning a test...

2020-10-03 18:49 UTC, ericgaspar commented on scripts/restore
> +mkdir -p "$final_path/app/sites/default/files"
and ... you're right  o.O

2020-10-07 01:15 UTC, zamentur approved these changes

2020-10-07 01:16 UTC, merged