Testing
YunoHost-Apps/framaforms_ynh pull request #39
Opened 2021-01-07 21:29 UTC by ericgaspar

- *Upgrade to version 1.0.3*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
*If you have access to [App Continuous Integration for packagers](https://yunohost.org/#/packaging_apps_ci) you can provide a link to the package_check results like below, replacing '-NUM-' in this link by the PR number and USERNAME by your username on the ci-apps-dev. Or you provide a screenshot or a pastebin of the results*

[![Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/framaforms_ynh%20PR-NUM-%20(USERNAME)/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/framaforms_ynh%20PR-NUM-%20(USERNAME)/)

2021-01-09 10:14 UTC, yalh76 requested changes

2021-01-09 10:14 UTC, yalh76 commented on manifest.json
> +  "version": "1.0.3~ynh1",
You should add an upgrade test from current version in https://github.com/YunoHost-Apps/framaforms_ynh/blob/testing/check_process

2021-01-09 12:17 UTC, yalh76 approved these changes
Just have to wait of a package_check test

2021-01-18 20:08 UTC, alexAubin commented
!testme

2021-01-18 21:58 UTC, tituspijean commented
Maybe all those warnings could be silenced? (cf. the test above)

2021-01-19 21:32 UTC, yalh76 approved these changes

2021-01-24 16:15 UTC, merged